// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: orders/orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductQuantity uint64                 `protobuf:"varint,2,opt,name=product_quantity,json=productQuantity,proto3" json:"product_quantity,omitempty"`
	PriceSnapshot   uint64                 `protobuf:"varint,3,opt,name=price_snapshot,json=priceSnapshot,proto3" json:"price_snapshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_orders_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetProductQuantity() uint64 {
	if x != nil {
		return x.ProductQuantity
	}
	return 0
}

func (x *OrderItem) GetPriceSnapshot() uint64 {
	if x != nil {
		return x.PriceSnapshot
	}
	return 0
}

type CreateNewOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderItems    []*OrderItem           `protobuf:"bytes,2,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewOrderRequest) Reset() {
	*x = CreateNewOrderRequest{}
	mi := &file_orders_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewOrderRequest) ProtoMessage() {}

func (x *CreateNewOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateNewOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNewOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNewOrderRequest) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type CreateNewOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewOrderResponse) Reset() {
	*x = CreateNewOrderResponse{}
	mi := &file_orders_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewOrderResponse) ProtoMessage() {}

func (x *CreateNewOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateNewOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNewOrderResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PayForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayForOrderRequest) Reset() {
	*x = PayForOrderRequest{}
	mi := &file_orders_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayForOrderRequest) ProtoMessage() {}

func (x *PayForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayForOrderRequest.ProtoReflect.Descriptor instead.
func (*PayForOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{3}
}

func (x *PayForOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_orders_orders_proto protoreflect.FileDescriptor

const file_orders_orders_proto_rawDesc = "" +
	"\n" +
	"\x13orders/orders.proto\x12\x06orders\x1a\x1bgoogle/protobuf/empty.proto\"|\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12)\n" +
	"\x10product_quantity\x18\x02 \x01(\x04R\x0fproductQuantity\x12%\n" +
	"\x0eprice_snapshot\x18\x03 \x01(\x04R\rpriceSnapshot\"d\n" +
	"\x15CreateNewOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x122\n" +
	"\vorder_items\x18\x02 \x03(\v2\x11.orders.OrderItemR\n" +
	"orderItems\"3\n" +
	"\x16CreateNewOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"/\n" +
	"\x12PayForOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId2\xa6\x01\n" +
	"\fOrderService\x12Q\n" +
	"\x0eCreateNewOrder\x12\x1d.orders.CreateNewOrderRequest\x1a\x1e.orders.CreateNewOrderResponse\"\x00\x12C\n" +
	"\vPayForOrder\x12\x1a.orders.PayForOrderRequest\x1a\x16.google.protobuf.Empty\"\x00B/Z-github.com/rogue0026/marketplace-proto/ordersb\x06proto3"

var (
	file_orders_orders_proto_rawDescOnce sync.Once
	file_orders_orders_proto_rawDescData []byte
)

func file_orders_orders_proto_rawDescGZIP() []byte {
	file_orders_orders_proto_rawDescOnce.Do(func() {
		file_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_orders_proto_rawDesc), len(file_orders_orders_proto_rawDesc)))
	})
	return file_orders_orders_proto_rawDescData
}

var file_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orders_orders_proto_goTypes = []any{
	(*OrderItem)(nil),              // 0: orders.OrderItem
	(*CreateNewOrderRequest)(nil),  // 1: orders.CreateNewOrderRequest
	(*CreateNewOrderResponse)(nil), // 2: orders.CreateNewOrderResponse
	(*PayForOrderRequest)(nil),     // 3: orders.PayForOrderRequest
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_orders_orders_proto_depIdxs = []int32{
	0, // 0: orders.CreateNewOrderRequest.order_items:type_name -> orders.OrderItem
	1, // 1: orders.OrderService.CreateNewOrder:input_type -> orders.CreateNewOrderRequest
	3, // 2: orders.OrderService.PayForOrder:input_type -> orders.PayForOrderRequest
	2, // 3: orders.OrderService.CreateNewOrder:output_type -> orders.CreateNewOrderResponse
	4, // 4: orders.OrderService.PayForOrder:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orders_orders_proto_init() }
func file_orders_orders_proto_init() {
	if File_orders_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_orders_proto_rawDesc), len(file_orders_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_orders_proto_goTypes,
		DependencyIndexes: file_orders_orders_proto_depIdxs,
		MessageInfos:      file_orders_orders_proto_msgTypes,
	}.Build()
	File_orders_orders_proto = out.File
	file_orders_orders_proto_goTypes = nil
	file_orders_orders_proto_depIdxs = nil
}
