// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: products/products.proto

package products

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RemainingStock uint64                 `protobuf:"varint,3,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"`
	CurrentPrice   uint64                 `protobuf:"varint,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetRemainingStock() uint64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

func (x *Product) GetCurrentPrice() uint64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

type ShowProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    uint64                 `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ItemsPerPage  uint64                 `protobuf:"varint,2,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProductsRequest) Reset() {
	*x = ShowProductsRequest{}
	mi := &file_products_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductsRequest) ProtoMessage() {}

func (x *ShowProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductsRequest.ProtoReflect.Descriptor instead.
func (*ShowProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{1}
}

func (x *ShowProductsRequest) GetPageNumber() uint64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ShowProductsRequest) GetItemsPerPage() uint64 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

type ShowProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProductsResponse) Reset() {
	*x = ShowProductsResponse{}
	mi := &file_products_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductsResponse) ProtoMessage() {}

func (x *ShowProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductsResponse.ProtoReflect.Descriptor instead.
func (*ShowProductsResponse) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{2}
}

func (x *ShowProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type AddProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RemainingStock uint64                 `protobuf:"varint,2,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"`
	CurrentPrice   uint64                 `protobuf:"varint,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_products_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{3}
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetRemainingStock() uint64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

func (x *AddProductRequest) GetCurrentPrice() uint64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_products_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{4}
}

func (x *AddProductResponse) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_products_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type IncreaseProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseProductRequest) Reset() {
	*x = IncreaseProductRequest{}
	mi := &file_products_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseProductRequest) ProtoMessage() {}

func (x *IncreaseProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseProductRequest.ProtoReflect.Descriptor instead.
func (*IncreaseProductRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{6}
}

func (x *IncreaseProductRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *IncreaseProductRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DecreaseProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseProductRequest) Reset() {
	*x = DecreaseProductRequest{}
	mi := &file_products_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseProductRequest) ProtoMessage() {}

func (x *DecreaseProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseProductRequest.ProtoReflect.Descriptor instead.
func (*DecreaseProductRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{7}
}

func (x *DecreaseProductRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DecreaseProductRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_products_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{8}
}

func (x *Reservation) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Reservation) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Reservation) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ReserveProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductsRequest) Reset() {
	*x = ReserveProductsRequest{}
	mi := &file_products_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsRequest) ProtoMessage() {}

func (x *ReserveProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveProductsRequest) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_products_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{10}
}

func (x *CancelReservationRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type DeleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationRequest) Reset() {
	*x = DeleteReservationRequest{}
	mi := &file_products_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationRequest) ProtoMessage() {}

func (x *DeleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteReservationRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_products_products_proto protoreflect.FileDescriptor

const file_products_products_proto_rawDesc = "" +
	"\n" +
	"\x17products/products.proto\x12\bproducts\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n" +
	"\aProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fremaining_stock\x18\x03 \x01(\x04R\x0eremainingStock\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x04R\fcurrentPrice\"\\\n" +
	"\x13ShowProductsRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x04R\n" +
	"pageNumber\x12$\n" +
	"\x0eitems_per_page\x18\x02 \x01(\x04R\fitemsPerPage\"E\n" +
	"\x14ShowProductsResponse\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.products.ProductR\bproducts\"u\n" +
	"\x11AddProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fremaining_stock\x18\x02 \x01(\x04R\x0eremainingStock\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x04R\fcurrentPrice\"3\n" +
	"\x12AddProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"5\n" +
	"\x14DeleteProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"O\n" +
	"\x16IncreaseProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"O\n" +
	"\x16DecreaseProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"_\n" +
	"\vReservation\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\"S\n" +
	"\x16ReserveProductsRequest\x129\n" +
	"\freservations\x18\x01 \x03(\v2\x15.products.ReservationR\freservations\"5\n" +
	"\x18CancelReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"5\n" +
	"\x18DeleteReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId2\x9a\x05\n" +
	"\x0eProductService\x12O\n" +
	"\fShowProducts\x12\x1d.products.ShowProductsRequest\x1a\x1e.products.ShowProductsResponse\"\x00\x12I\n" +
	"\n" +
	"AddProduct\x12\x1b.products.AddProductRequest\x1a\x1c.products.AddProductResponse\"\x00\x12I\n" +
	"\rDeleteProduct\x12\x1e.products.DeleteProductRequest\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x17IncreaseProductQuantity\x12 .products.IncreaseProductRequest\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x17DecreaseProductQuantity\x12 .products.DecreaseProductRequest\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\x0fReserveProducts\x12 .products.ReserveProductsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Q\n" +
	"\x11CancelReservation\x12\".products.CancelReservationRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Q\n" +
	"\x11DeleteReservation\x12\".products.DeleteReservationRequest\x1a\x16.google.protobuf.Empty\"\x00B1Z/github.com/rogue0026/marketplace-proto/productsb\x06proto3"

var (
	file_products_products_proto_rawDescOnce sync.Once
	file_products_products_proto_rawDescData []byte
)

func file_products_products_proto_rawDescGZIP() []byte {
	file_products_products_proto_rawDescOnce.Do(func() {
		file_products_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_products_proto_rawDesc), len(file_products_products_proto_rawDesc)))
	})
	return file_products_products_proto_rawDescData
}

var file_products_products_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_products_products_proto_goTypes = []any{
	(*Product)(nil),                  // 0: products.Product
	(*ShowProductsRequest)(nil),      // 1: products.ShowProductsRequest
	(*ShowProductsResponse)(nil),     // 2: products.ShowProductsResponse
	(*AddProductRequest)(nil),        // 3: products.AddProductRequest
	(*AddProductResponse)(nil),       // 4: products.AddProductResponse
	(*DeleteProductRequest)(nil),     // 5: products.DeleteProductRequest
	(*IncreaseProductRequest)(nil),   // 6: products.IncreaseProductRequest
	(*DecreaseProductRequest)(nil),   // 7: products.DecreaseProductRequest
	(*Reservation)(nil),              // 8: products.Reservation
	(*ReserveProductsRequest)(nil),   // 9: products.ReserveProductsRequest
	(*CancelReservationRequest)(nil), // 10: products.CancelReservationRequest
	(*DeleteReservationRequest)(nil), // 11: products.DeleteReservationRequest
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_products_products_proto_depIdxs = []int32{
	0,  // 0: products.ShowProductsResponse.products:type_name -> products.Product
	8,  // 1: products.ReserveProductsRequest.reservations:type_name -> products.Reservation
	1,  // 2: products.ProductService.ShowProducts:input_type -> products.ShowProductsRequest
	3,  // 3: products.ProductService.AddProduct:input_type -> products.AddProductRequest
	5,  // 4: products.ProductService.DeleteProduct:input_type -> products.DeleteProductRequest
	6,  // 5: products.ProductService.IncreaseProductQuantity:input_type -> products.IncreaseProductRequest
	7,  // 6: products.ProductService.DecreaseProductQuantity:input_type -> products.DecreaseProductRequest
	9,  // 7: products.ProductService.ReserveProducts:input_type -> products.ReserveProductsRequest
	10, // 8: products.ProductService.CancelReservation:input_type -> products.CancelReservationRequest
	11, // 9: products.ProductService.DeleteReservation:input_type -> products.DeleteReservationRequest
	2,  // 10: products.ProductService.ShowProducts:output_type -> products.ShowProductsResponse
	4,  // 11: products.ProductService.AddProduct:output_type -> products.AddProductResponse
	12, // 12: products.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	12, // 13: products.ProductService.IncreaseProductQuantity:output_type -> google.protobuf.Empty
	12, // 14: products.ProductService.DecreaseProductQuantity:output_type -> google.protobuf.Empty
	12, // 15: products.ProductService.ReserveProducts:output_type -> google.protobuf.Empty
	12, // 16: products.ProductService.CancelReservation:output_type -> google.protobuf.Empty
	12, // 17: products.ProductService.DeleteReservation:output_type -> google.protobuf.Empty
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_products_products_proto_init() }
func file_products_products_proto_init() {
	if File_products_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_products_proto_rawDesc), len(file_products_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_products_proto_goTypes,
		DependencyIndexes: file_products_products_proto_depIdxs,
		MessageInfos:      file_products_products_proto_msgTypes,
	}.Build()
	File_products_products_proto = out.File
	file_products_products_proto_goTypes = nil
	file_products_products_proto_depIdxs = nil
}
