// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasketProduct struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId       uint64                 `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductQuantity uint64                 `protobuf:"varint,4,opt,name=product_quantity,json=productQuantity,proto3" json:"product_quantity,omitempty"`
	PricePerUnit    uint64                 `protobuf:"varint,5,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BasketProduct) Reset() {
	*x = BasketProduct{}
	mi := &file_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketProduct) ProtoMessage() {}

func (x *BasketProduct) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketProduct.ProtoReflect.Descriptor instead.
func (*BasketProduct) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *BasketProduct) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BasketProduct) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BasketProduct) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *BasketProduct) GetProductQuantity() uint64 {
	if x != nil {
		return x.ProductQuantity
	}
	return 0
}

func (x *BasketProduct) GetPricePerUnit() uint64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddMoneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMoneyRequest) Reset() {
	*x = AddMoneyRequest{}
	mi := &file_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMoneyRequest) ProtoMessage() {}

func (x *AddMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMoneyRequest.ProtoReflect.Descriptor instead.
func (*AddMoneyRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *AddMoneyRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddMoneyRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WriteOffMoneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOffMoneyRequest) Reset() {
	*x = WriteOffMoneyRequest{}
	mi := &file_users_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOffMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOffMoneyRequest) ProtoMessage() {}

func (x *WriteOffMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOffMoneyRequest.ProtoReflect.Descriptor instead.
func (*WriteOffMoneyRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{5}
}

func (x *WriteOffMoneyRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WriteOffMoneyRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetProductsFromBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsFromBasketRequest) Reset() {
	*x = GetProductsFromBasketRequest{}
	mi := &file_users_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsFromBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsFromBasketRequest) ProtoMessage() {}

func (x *GetProductsFromBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsFromBasketRequest.ProtoReflect.Descriptor instead.
func (*GetProductsFromBasketRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductsFromBasketRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProductsFromBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BasketItems   []*BasketProduct       `protobuf:"bytes,2,rep,name=basket_items,json=basketItems,proto3" json:"basket_items,omitempty"`
	TotalPrice    uint64                 `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsFromBasketResponse) Reset() {
	*x = GetProductsFromBasketResponse{}
	mi := &file_users_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsFromBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsFromBasketResponse) ProtoMessage() {}

func (x *GetProductsFromBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsFromBasketResponse.ProtoReflect.Descriptor instead.
func (*GetProductsFromBasketResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductsFromBasketResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProductsFromBasketResponse) GetBasketItems() []*BasketProduct {
	if x != nil {
		return x.BasketItems
	}
	return nil
}

func (x *GetProductsFromBasketResponse) GetTotalPrice() uint64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type AddProductsToBasketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId       uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductQuantity uint64                 `protobuf:"varint,3,opt,name=product_quantity,json=productQuantity,proto3" json:"product_quantity,omitempty"`
	PricePerUnit    uint64                 `protobuf:"varint,4,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddProductsToBasketRequest) Reset() {
	*x = AddProductsToBasketRequest{}
	mi := &file_users_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToBasketRequest) ProtoMessage() {}

func (x *AddProductsToBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToBasketRequest.ProtoReflect.Descriptor instead.
func (*AddProductsToBasketRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{8}
}

func (x *AddProductsToBasketRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddProductsToBasketRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProductsToBasketRequest) GetProductQuantity() uint64 {
	if x != nil {
		return x.ProductQuantity
	}
	return 0
}

func (x *AddProductsToBasketRequest) GetPricePerUnit() uint64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

type ClearUserBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUserBasketRequest) Reset() {
	*x = ClearUserBasketRequest{}
	mi := &file_users_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUserBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUserBasketRequest) ProtoMessage() {}

func (x *ClearUserBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUserBasketRequest.ProtoReflect.Descriptor instead.
func (*ClearUserBasketRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{9}
}

func (x *ClearUserBasketRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_users_users_proto protoreflect.FileDescriptor

const file_users_users_proto_rawDesc = "" +
	"\n" +
	"\x11users/users.proto\x12\x05users\x1a\x1bgoogle/protobuf/empty.proto\"\xa8\x01\n" +
	"\rBasketProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x04R\tproductId\x12)\n" +
	"\x10product_quantity\x18\x04 \x01(\x04R\x0fproductQuantity\x12$\n" +
	"\x0eprice_per_unit\x18\x05 \x01(\x04R\fpricePerUnit\"E\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"B\n" +
	"\x0fAddMoneyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"G\n" +
	"\x14WriteOffMoneyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"7\n" +
	"\x1cGetProductsFromBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x92\x01\n" +
	"\x1dGetProductsFromBasketResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x127\n" +
	"\fbasket_items\x18\x02 \x03(\v2\x14.users.BasketProductR\vbasketItems\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x04R\n" +
	"totalPrice\"\xa5\x01\n" +
	"\x1aAddProductsToBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12)\n" +
	"\x10product_quantity\x18\x03 \x01(\x04R\x0fproductQuantity\x12$\n" +
	"\x0eprice_per_unit\x18\x04 \x01(\x04R\fpricePerUnit\"1\n" +
	"\x16ClearUserBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId2\x9f\x04\n" +
	"\vUserService\x12C\n" +
	"\n" +
	"CreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x00\x12@\n" +
	"\n" +
	"DeleteUser\x12\x18.users.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\bAddMoney\x12\x16.users.AddMoneyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\rWriteOffMoney\x12\x1b.users.WriteOffMoneyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12d\n" +
	"\x15GetProductsFromBasket\x12#.users.GetProductsFromBasketRequest\x1a$.users.GetProductsFromBasketResponse\"\x00\x12Q\n" +
	"\x12AddProductToBasket\x12!.users.AddProductsToBasketRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0fClearUserBasket\x12\x1d.users.ClearUserBasketRequest\x1a\x16.google.protobuf.Empty\"\x00B.Z,github.com/rogue0026/marketplace-proto/usersb\x06proto3"

var (
	file_users_users_proto_rawDescOnce sync.Once
	file_users_users_proto_rawDescData []byte
)

func file_users_users_proto_rawDescGZIP() []byte {
	file_users_users_proto_rawDescOnce.Do(func() {
		file_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)))
	})
	return file_users_users_proto_rawDescData
}

var file_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_users_users_proto_goTypes = []any{
	(*BasketProduct)(nil),                 // 0: users.BasketProduct
	(*CreateUserRequest)(nil),             // 1: users.CreateUserRequest
	(*CreateUserResponse)(nil),            // 2: users.CreateUserResponse
	(*DeleteUserRequest)(nil),             // 3: users.DeleteUserRequest
	(*AddMoneyRequest)(nil),               // 4: users.AddMoneyRequest
	(*WriteOffMoneyRequest)(nil),          // 5: users.WriteOffMoneyRequest
	(*GetProductsFromBasketRequest)(nil),  // 6: users.GetProductsFromBasketRequest
	(*GetProductsFromBasketResponse)(nil), // 7: users.GetProductsFromBasketResponse
	(*AddProductsToBasketRequest)(nil),    // 8: users.AddProductsToBasketRequest
	(*ClearUserBasketRequest)(nil),        // 9: users.ClearUserBasketRequest
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
}
var file_users_users_proto_depIdxs = []int32{
	0,  // 0: users.GetProductsFromBasketResponse.basket_items:type_name -> users.BasketProduct
	1,  // 1: users.UserService.CreateUser:input_type -> users.CreateUserRequest
	3,  // 2: users.UserService.DeleteUser:input_type -> users.DeleteUserRequest
	4,  // 3: users.UserService.AddMoney:input_type -> users.AddMoneyRequest
	5,  // 4: users.UserService.WriteOffMoney:input_type -> users.WriteOffMoneyRequest
	6,  // 5: users.UserService.GetProductsFromBasket:input_type -> users.GetProductsFromBasketRequest
	8,  // 6: users.UserService.AddProductToBasket:input_type -> users.AddProductsToBasketRequest
	9,  // 7: users.UserService.ClearUserBasket:input_type -> users.ClearUserBasketRequest
	2,  // 8: users.UserService.CreateUser:output_type -> users.CreateUserResponse
	10, // 9: users.UserService.DeleteUser:output_type -> google.protobuf.Empty
	10, // 10: users.UserService.AddMoney:output_type -> google.protobuf.Empty
	10, // 11: users.UserService.WriteOffMoney:output_type -> google.protobuf.Empty
	7,  // 12: users.UserService.GetProductsFromBasket:output_type -> users.GetProductsFromBasketResponse
	10, // 13: users.UserService.AddProductToBasket:output_type -> google.protobuf.Empty
	10, // 14: users.UserService.ClearUserBasket:output_type -> google.protobuf.Empty
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_users_users_proto_init() }
func file_users_users_proto_init() {
	if File_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_users_proto_goTypes,
		DependencyIndexes: file_users_users_proto_depIdxs,
		MessageInfos:      file_users_users_proto_msgTypes,
	}.Build()
	File_users_users_proto = out.File
	file_users_users_proto_goTypes = nil
	file_users_users_proto_depIdxs = nil
}
